
apiVersion: apps/v1 #Deployment
kind: Deployment
metadata:
  name: deploy-next
  namespace: frontend
  labels:
    app: deploy-django
spec:
  replicas: 1 #replicaSets
  selector:
    matchLabels:
      app: next
  template: #Pod
    metadata:
      labels:
        app: next
    spec:
      containers:
        - name: next
          image: localhost:5000/next:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: frontend
spec:
  selector:
    app: next
  ports:
    - name: next
      protocol: TCP
      port: 3000
      targetPort: 3000
