
apiVersion: apps/v1 #Deployment
kind: Deployment
metadata:
  name: deploy-nginx
  namespace: frontend
  labels:
    app: deploy-nginx
spec:
  replicas: 1 #replicaSets
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: localhost:5000/nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: frontend
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80

---

