apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-next
  namespace: frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: next.com
      http:
        paths:
          - backend:
              serviceName: nginx-next
              servicePort: 8080
